### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by curioussavage** [blessed-ng/blessed#1]
hello,

Just noticed this was created today, I think good first step is moving the documentation out of the readme. Its a little hard to browse through them right now. Github pages might be a good solution. It probably makes sense to put them in their own repo and use github pages since you might break out the widgets into their own repo. If you create the repo I will move everything over. 

thoughts?

**Comment by piranna** [comment]
Github now support [publish from the docs folder](https://github.com/blog/2228-simpler-github-pages-publishing), so I think we could move the documentation from the README file to its own markdown file there, and later adapt it to follow GitBook format. If you want to split the documentation there pull-requests are welcome :-)

**Comment by curioussavage** [comment]
So it sounds like you would be more in favor of using gitbook for hosting a documentation site? Do they have themes? The default one is pretty crappy. I only bring it up because I think the hacker theme for github pages would be pretty sweet.

**Comment by piranna** [comment]
They are not incompatible, by using the `docs` folder we can publish it both on Github Pages (with the hacker theme, for example :-) ) and have it ready for print with GitBook. Win-win :-)

**Comment by curioussavage** [comment]
From looking at the docs for both projects it looks like they are only compatible on the surface. If we wanted to have a decent doc site with jekyl we would need to put a theme in the dir that has navigation. Plus stuff for search if we want that.  

Gitbook has that for free so seems much better. We could still host the site on github but the docs directory would need to be the output of the Gitbook tool instead of the markdown. Or would you prefer to host it on Gitbooks platform?

**Comment by curioussavage** [comment]
Also I see that blessedjs .com/.org are available. I would be willing to buy the domain if that sounds good.

**Comment by piranna** [comment]
> From looking at the docs for both projects it looks like they are only compatible on the surface. If we wanted to have a decent doc site with jekyl we would need to put a theme in the dir that has navigation. Plus stuff for search if we want that.

I don't think it would be so much difficult, but we could start by writting the pages for the docs and later see how to improve them.


> Also I see that blessedjs .com/.org are available. I would be willing to buy the domain if that sounds good.

That would be cool! :-)

**Comment by piranna** [comment]
Fixed in master, clossing.
